// AUTO-GENERATED by onreza-release
// Run: onreza-release generate-commitlint
// DO NOT EDIT MANUALLY - Changes will be overwritten

const config = {
  parserPreset: { // Support for feat(scope)!, fix! breaking change syntax
    name: "conventional-changelog-conventionalcommits",
    parserOpts: {
      headerPattern: /^(\w*)(?:\((.*)\))?!?: (.*)$/,
      breakingHeaderPattern: /^(\w*)(?:\((.*)\))?!: (.*)$/,
      headerCorrespondence: ["type", "scope", "subject"],
      noteKeywords: ["BREAKING CHANGE", "BREAKING-CHANGE"],
      revertPattern: /^(?:Revert|revert:)\s"?([\s\S]+?)"?\s*This reverts commit (\w*)\./i,
      revertCorrespondence: ["header", "hash"],
    },
  },

  rules: {
    "type-enum": [2, "always", ["build","chore","ci","docs","feat","fix","perf","refactor","revert","style","test"]],
    "type-empty": [2, "never"],
    "type-case": [2, "always", "lower-case"],
    "scope-enum": [2, "always", ["build","ci","cli","db","deploy","deps","dev","docs","emulator","kv","release","tests"]],
    "scope-empty": [0], // scope optional
    "subject-case": [0], // disabled - any case allowed
    "subject-empty": [2, "never"],
    "subject-full-stop": [2, "never", "."],
    "header-max-length": [1, "always", 100], // warning
    "header-trim": [2, "always"],
    "body-leading-blank": [2, "always"],
    "body-max-line-length": [2, "always", 100],
    "footer-leading-blank": [2, "always"],
    "footer-max-line-length": [2, "always", 100],
  },
};

module.exports = config;
