/// Generate a JS bootstrap script that sets up `globalThis.ONREZA`
/// with local emulator backends (KV, Context).
///
/// The generated script is injected before the framework's dev server starts
/// via Node.js `--require` / `--import` flag.
pub fn generate_bootstrap(emulator_url: &str, token: &str) -> anyhow::Result<String> {
    let emulator_url = serde_json::to_string(emulator_url)?;
    let token = serde_json::to_string(token)?;

    let script = format!(
        r#"// Auto-generated by nrz dev — do not edit
const NRZ_EMULATOR = {emulator_url};
const NRZ_EMULATOR_TOKEN = {token};

async function __nrzFetch(url, options, operation) {{
  const res = await fetch(url, options).catch(e => {{
    throw new Error(`[nrz] ${{operation}} failed: is nrz dev running? (${{e.message}})`);
  }});
  if (!res.ok) {{
    const text = await res.text();
    throw new Error(`[nrz] ${{operation}} returned ${{res.status}}: ${{text}}`);
  }}
  return res;
}}

globalThis.ONREZA = {{
  __emulatorUrl: NRZ_EMULATOR,
  env: new Map(Object.entries(process.env)),
  context: {{
    clientIp: "127.0.0.1",
    geo: {{ country: "XX", city: "Local", continent: "XX", region: "local" }},
    deploymentId: "dev",
    projectId: "dev",
    commitSha: "dev",
    requestId: null,
  }},
  // KV is proxied to nrz emulator HTTP API
  kv: new Proxy({{}}, {{
    get(_, method) {{
      return async (...args) => {{
        const res = await __nrzFetch(`${{NRZ_EMULATOR}}/__nrz/kv/${{method}}`, {{
          method: "POST",
          headers: {{
            "content-type": "application/json",
            "x-nrz-emulator-token": NRZ_EMULATOR_TOKEN,
          }},
          body: JSON.stringify({{ args }}),
        }}, `kv.${{method}}`);
        return res.json();
      }};
    }},
  }}),
}};

console.log("[nrz] ONREZA runtime emulator injected");
"#,
        emulator_url = emulator_url,
        token = token,
    );

    Ok(script)
}
