use std::path::Path;

/// Generate a JS bootstrap script that sets up `globalThis.ONREZA`
/// with local emulator backends (KV, DB, Context).
///
/// The generated script is injected before the framework's dev server starts
/// via Node.js `--require` / `--import` flag.
pub fn generate_bootstrap(data_dir: &Path, port: u16) -> anyhow::Result<String> {
    let db_path = data_dir.join("dev.db");

    // The bootstrap connects to nrz's emulator HTTP API
    // running on a local port, providing KV/DB/Context operations.
    let script = format!(
        r#"// Auto-generated by nrz dev — do not edit
const NRZ_EMULATOR = "http://127.0.0.1:{port}";
const DB_PATH = {db_path};

async function __nrzFetch(url, options, operation) {{
  const res = await fetch(url, options).catch(e => {{
    throw new Error(`[nrz] ${{operation}} failed: is nrz dev running? (${{e.message}})`);
  }});
  if (!res.ok) {{
    const text = await res.text();
    throw new Error(`[nrz] ${{operation}} returned ${{res.status}}: ${{text}}`);
  }}
  return res;
}}

globalThis.ONREZA = {{
  env: new Map(Object.entries(process.env)),
  context: {{
    clientIp: "127.0.0.1",
    geo: {{ country: "XX", city: "Local", continent: "XX", region: "local" }},
    deploymentId: "dev",
    projectId: "dev",
    commitSha: "dev",
    requestId: null,
  }},
  // KV and DB are proxied to nrz emulator HTTP API
  kv: new Proxy({{}}, {{
    get(_, method) {{
      return async (...args) => {{
        const res = await __nrzFetch(`${{NRZ_EMULATOR}}/__nrz/kv/${{method}}`, {{
          method: "POST",
          headers: {{ "content-type": "application/json" }},
          body: JSON.stringify({{ args }}),
        }}, `kv.${{method}}`);
        return res.json();
      }};
    }},
  }}),
  db: new Proxy({{}}, {{
    get(_, method) {{
      if (method === "prepare") {{
        return (sql) => {{
          let bindings = [];
          return {{
            bind(...args) {{ bindings = args; return this; }},
            async all() {{
              const res = await __nrzFetch(`${{NRZ_EMULATOR}}/__nrz/db/query`, {{
                method: "POST",
                headers: {{ "content-type": "application/json" }},
                body: JSON.stringify({{ sql, bindings, mode: "all" }}),
              }}, "db.prepare().all");
              return res.json();
            }},
            async first(col) {{
              const res = await __nrzFetch(`${{NRZ_EMULATOR}}/__nrz/db/query`, {{
                method: "POST",
                headers: {{ "content-type": "application/json" }},
                body: JSON.stringify({{ sql, bindings, mode: "first", column: col }}),
              }}, "db.prepare().first");
              return res.json();
            }},
            async run() {{
              const res = await __nrzFetch(`${{NRZ_EMULATOR}}/__nrz/db/query`, {{
                method: "POST",
                headers: {{ "content-type": "application/json" }},
                body: JSON.stringify({{ sql, bindings, mode: "run" }}),
              }}, "db.prepare().run");
              return res.json();
            }},
            async raw(opts) {{
              const res = await __nrzFetch(`${{NRZ_EMULATOR}}/__nrz/db/query`, {{
                method: "POST",
                headers: {{ "content-type": "application/json" }},
                body: JSON.stringify({{ sql, bindings, mode: "raw", columnNames: opts?.columnNames }}),
              }}, "db.prepare().raw");
              return res.json();
            }},
          }};
        }};
      }}
      if (method === "batch") {{
        return async (stmts) => {{
          const res = await __nrzFetch(`${{NRZ_EMULATOR}}/__nrz/db/batch`, {{
            method: "POST",
            headers: {{ "content-type": "application/json" }},
            body: JSON.stringify({{ statements: stmts }}),
          }}, "db.batch");
          return res.json();
        }};
      }}
      if (method === "exec") {{
        return async (sql) => {{
          const res = await __nrzFetch(`${{NRZ_EMULATOR}}/__nrz/db/exec`, {{
            method: "POST",
            headers: {{ "content-type": "application/json" }},
            body: JSON.stringify({{ sql }}),
          }}, "db.exec");
          return res.json();
        }};
      }}
    }},
  }}),
}};

console.log("[nrz] ONREZA runtime emulator injected");
"#,
        port = port,
        db_path = serde_json::to_string(db_path.to_str().ok_or_else(|| {
            anyhow::anyhow!(
                "project path contains invalid UTF-8: {}. Move project to a UTF-8 path.",
                db_path.display()
            )
        })?)?,
    );

    Ok(script)
}
